kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: observatory
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            authorization-mode: AlwaysAllow
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
