apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: observatory-system
  labels:
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: observatory-controller
      containers:
        - name: manager
          image: observatory-operator:dev
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          ports:
            - containerPort: 9443
              name: webhook-server
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
