apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: observatory-validating-webhook-configuration
webhooks:
- name: vobservatoryrun.kb.io
  admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: observatory-webhook-service
      namespace: observatory-system
      path: /validate-observatory-seventh-horizon-io-v1alpha1-observatoryrun
  failurePolicy: Fail
  rules:
  - apiGroups: ["observatory.seventh-horizon.io"]
    apiVersions: ["v1alpha1"]
    operations: ["CREATE","UPDATE"]
    resources: ["observatoryruns"]
  sideEffects: None
---
apiVersion: v1
kind: Service
metadata:
  name: observatory-webhook-service
  namespace: observatory-system
spec:
  selector:
    control-plane: controller-manager
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
