apiVersion: v1
kind: Service
metadata:
  name: observatory-webhook-service
  namespace: observatory-system
spec:
  selector:
    control-plane: controller-manager
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
    name: https
