---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observatory-controller-metrics
  namespace: observatory-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
