apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: observatoryruns.observatory.seventh-horizon.io
spec:
  group: observatory.seventh-horizon.io
  scope: Namespaced
  names:
    plural: observatoryruns
    singular: observatoryrun
    kind: ObservatoryRun
    shortNames: ["obsrun", "obr"]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["project", "workflow"]
              properties:
                project:
                  type: string
                resources:
                  type: object
                  additionalProperties: true
                observability:
                  type: object
                  additionalProperties: true
                workflow:
                  type: object
                  properties:
                    tasks:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          type:
                            type: string
                          image:
                            type: string
                          command:
                            type: string
                          args:
                            type: array
                            items: { type: string }
                          dependencies:
                            type: array
                            items: { type: string }
                          retries:
                            type: integer
                    failurePolicy:
                      type: string
                      enum:
                        - Continue
                        - Stop
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: Overall phase of the run (e.g., Pending, Running, Succeeded, Failed)
                taskStatuses:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      state:
                        type: string
                      jobName:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
