name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install -U pip
          # If you don’t have a requirements.txt, this will be a no-op.
          pip install -r requirements.txt || true
          pip install pytest jsonschema
      - run: pytest -q
