name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install pytest jsonschema

      - name: Run tests
        run: pytest -q

      - name: Upload sample artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verify-samples
          path: |
            out/verify_stats.csv
            out/verify_stats.sample.json
            out/anomalies.jsonl
          if-no-files-found: ignore