
name: Timeline Build
on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]
jobs:
  timeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Build snapshot (placeholder)
        run: |
          python - <<'PY'
print("timeline snapshot would be built here")
PY
      - name: Validate (placeholder)
        run: echo "validate timeline"
